export const CHANGE_FILMS = 'FILTER_FILMS';

export const CHANGE_REGISTER_MODAL = 'CHANGE_REGISTER_MODAL';
export const CHANGE_REGISTER_MESSAGE = 'CHANGE_REGISTER_MESSAGE';
export const CHANGE_FILM = 'CHANGE_FILM';
export const CHANGE_DESCRIPTION_MODAL = 'CHANGE_DESCRIPTION_MODAL';
export const GET_RATE = 'GET_RATE';
export const CHANGE_DESCRIPTION_MESSAGE = 'CHANGE_DESCRIPTION_MESSAGE';
export const CHANGE_PUT_REPORT_MESSAGE = 'CHANGE_PUT_REPORT_MESSAGE';

const HOST = `http://localhost`;
const PORT = `3000`;
const API_V1 = `api/v1`;
export const BASE_URL = `${HOST}:${PORT}/${API_V1}`;
