version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: fucinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
